# Generated by Django 5.2.7 on 2025-10-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero_telefono',
            field=models.CharField(max_length=15, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
    ]
