# Generated by Django 5.2.7 on 2025-10-30 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('emoji', models.CharField(blank=True, max_length=5)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActividadFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidad', models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('intenso', 'Intenso')], max_length=50)),
                ('duracion_sesiones', models.IntegerField()),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad Física',
                'verbose_name_plural': 'Actividades Físicas',
            },
        ),
        migrations.CreateModel(
            name='AlimentosConsumidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('consumo', models.BooleanField(default=False)),
                ('numero_comidas_dia', models.IntegerField()),
                ('snacks_dia', models.IntegerField()),
                ('calorias_totales', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alimento Consumido',
                'verbose_name_plural': 'Alimentos Consumidos',
            },
        ),
        migrations.CreateModel(
            name='CaracteristicasFisicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura en metros (ej: 1.75)', max_digits=4)),
                ('imc', models.DecimalField(decimal_places=2, editable=False, max_digits=4)),
                ('condicion_fisica', models.CharField(max_length=100)),
                ('enfermedades', models.TextField()),
                ('alergias', models.TextField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Características Físicas',
                'verbose_name_plural': 'Características Físicas',
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaComidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('snacks', 'Snacks')], max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Frecuencia de Comida',
                'verbose_name_plural': 'Frecuencias de Comidas',
            },
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_peso', models.CharField(choices=[('perder', 'Perder peso'), ('mantener', 'Mantener peso'), ('ganar', 'Ganar peso')], max_length=10)),
                ('plazo_meses', models.IntegerField()),
                ('peso_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_receta', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('instrucciones', models.TextField()),
                ('calorias', models.IntegerField()),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('carbohidratos', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='RestriccionesDietarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarianismo', models.BooleanField(default=False)),
                ('veganismo', models.BooleanField(default=False)),
                ('restricciones_economicas', models.BooleanField(default=False)),
                ('alergias_alimentarias', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restricción Dietaria',
                'verbose_name_plural': 'Restricciones Dietarias',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAlimentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferencia', models.CharField(choices=[('like', '😋 Me gusta'), ('dislike', '😐 No me gusta'), ('allergy', '🚫 No puedo consumir'), ('restrict', '⚠️ Evitar por recomendación')], max_length=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.alimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restriccion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.restriccionesdietarias')),
            ],
            options={
                'unique_together': {('usuario', 'alimento')},
            },
        ),
    ]
