# Generated by Django 5.2.7 on 2025-11-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frecuenciacomidas',
            name='frecuencia',
            field=models.CharField(max_length=100),
        ),
    ]
