# Generated by Django 5.2.7 on 2025-11-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_actividad_delete_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
