# Generated by Django 5.2.7 on 2025-11-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_actividad_notificado_actividad_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='notificado',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='usuario',
        ),
    ]
